In [8]:
import pandas as pd

# 读取员工数据
df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\employees.csv")
df

# 按照部门id进行分组
group_by = df.groupby('department_id')
group_by

## 1)查看分组

In [2]:
group_by.groups     # 返回一个字典，字典的键是分组的标签，值是属于该组的所有索引的列表。
group_by.get_group(30)  # 获取分组

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
14,114,Den,Raphaely,DRAPHEAL,515.127.4561,PU_MAN,11000.0,NaN,100.0,30.0
15,115,Alexander,Khoo,AKHOO,515.127.4562,PU_CLERK,3100.0,NaN,114.0,30.0
16,116,Shelli,Baida,SBAIDA,515.127.4563,PU_CLERK,2900.0,NaN,114.0,30.0
17,117,Sigal,Tobias,STOBIAS,515.127.4564,PU_CLERK,2800.0,NaN,114.0,30.0
18,118,Guy,Himuro,GHIMURO,515.127.4565,PU_CLERK,2600.0,NaN,114.0,30.0
19,119,Karen,Colmenares,KCOLMENA,515.127.4566,PU_CLERK,2500.0,NaN,114.0,30.0

## 2)按列分组

In [3]:
group_by[['salary']]

## 3)按组迭代

In [4]:
for dept_id,group in group_by:
    print(f"当前组为{dept_id}，组里的数据情况{group.shape}:")
    print(group.iloc[:,0:3])
    print("-------------------")

当前组为10.0，组里的数据情况(1, 10):
     employee_id first_name last_name
100          200   Jennifer    Whalen
-------------------
当前组为20.0，组里的数据情况(2, 10):
     employee_id first_name  last_name
101          201    Michael  Hartstein
102          202        Pat        Fay
-------------------
当前组为30.0，组里的数据情况(6, 10):
    employee_id first_name   last_name
14          114        Den    Raphaely
15          115  Alexander        Khoo
16          116     Shelli       Baida
17          117      Sigal      Tobias
18          118        Guy      Himuro
19          119      Karen  Colmenares
-------------------
当前组为40.0，组里的数据情况(1, 10):
     employee_id first_name last_name
103          203      Susan    Mavris
-------------------
当前组为50.0，组里的数据情况(45, 10):
    employee_id first_name    last_name
20          120    Matthew        Weiss
21          121       Adam        Fripp
22          122      Payam     Kaufling
23          123     Shanta      Vollman
24          124      Kevin      Mourgos
25          125      Julia        Nayer
26          126      Irene  Mikkilineni
27          127      James       Landry
28          128     Steven       Markle
29          129      Laura       Bissot
30          130      Mozhe     Atkinson
31          131      James       Marlow
32          132         TJ        Olson
33          133      Jason       Mallin
34          134    Michael       Rogers
35          135         Ki          Gee
36          136      Hazel   Philtanker
37          137     Renske       Ladwig
38          138    Stephen       Stiles
39          139       John          Seo
40          140     Joshua        Patel
41          141     Trenna         Rajs
42          142     Curtis       Davies
43          143    Randall        Matos
44          144      Peter       Vargas
80          180    Winston       Taylor
81          181       Jean       Fleaur
82          182     Martha     Sullivan
83          183     Girard        Geoni
84          184    Nandita     Sarchand
85          185     Alexis         Bull
86          186      Julia    Dellinger
87          187    Anthony       Cabrio
88          188      Kelly        Chung
89          189   Jennifer        Dilly
90          190    Timothy        Gates
91          191    Randall      Perkins
92          192      Sarah         Bell
93          193    Britney      Everett
94          194     Samuel       McCain
95          195      Vance        Jones
96          196      Alana        Walsh
97          197      Kevin       Feeney
98          198     Donald     OConnell
99          199    Douglas        Grant
-------------------
当前组为60.0，组里的数据情况(5, 10):
   employee_id first_name  last_name
3          103  Alexander     Hunold
4          104      Bruce      Ernst
5          105      David     Austin
6          106      Valli  Pataballa
7          107      Diana    Lorentz
-------------------
当前组为70.0，组里的数据情况(1, 10):
     employee_id first_name last_name
104          204    Hermann      Baer
-------------------
当前组为80.0，组里的数据情况(34, 10):
    employee_id   first_name   last_name
45          145         John     Russell
46          146        Karen    Partners
47          147      Alberto   Errazuriz
48          148       Gerald   Cambrault
49          149        Eleni     Zlotkey
50          150        Peter      Tucker
51          151        David   Bernstein
52          152        Peter        Hall
53          153  Christopher       Olsen
54          154      Nanette   Cambrault
55          155       Oliver     Tuvault
56          156      Janette        King
57          157      Patrick       Sully
58          158        Allan      McEwen
59          159      Lindsey       Smith
60          160       Louise       Doran
61          161       Sarath      Sewall
62          162        Clara     Vishney
63          163     Danielle      Greene
64          164       Mattea     Marvins
65          165        David         Lee
66          166       Sundar        Ande
67          167         Amit       Banda
68          168         Lisa        Ozer
69          169     Harrison       Bloom
70          170       Tayler         Fox
71          171      William       Smith
72          172    Elizabeth       Bates
73          173      Sundita       Kumar
74          174        Ellen        Abel
75          175       Alyssa      Hutton
76          176     Jonathon      Taylor
77          177         Jack  Livingston
79          179      Charles     Johnson
-------------------
当前组为90.0，组里的数据情况(3, 10):
   employee_id first_name last_name
0          100     Steven      King
1          101      N_ann   Kochhar
2          102        Lex   De Haan
-------------------
当前组为100.0，组里的数据情况(6, 10):
    employee_id   first_name  last_name
8           108        Nancy  Greenberg
9           109       Daniel     Faviet
10          110         John       Chen
11          111       Ismael    Sciarra
12          112  Jose Manuel      Urman
13          113         Luis       Popp
-------------------
当前组为110.0，组里的数据情况(2, 10):
     employee_id first_name last_name
105          205    Shelley   Higgins
106          206    William     Gietz
-------------------

## 4)按多字段分组

In [5]:
salary_mean = df.groupby(['department_id','job_id'])[['salary','commission_pct']].mean()
salary_mean.info()      # 按多个字段分组后得到的索引为复合索引
salary_mean.reset_index()

# 也可以在分组的时候通过as_index = False参数（默认是True）重置索引
salary_mean1 = df.groupby(["department_id", "job_id"], as_index=False)[["salary", "commission_pct"]].mean()
salary_mean1

<class 'pandas.DataFrame'>
MultiIndex: 19 entries, (np.float64(10.0), 'AD_ASST') to (np.float64(110.0), 'AC_MGR')
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   salary          19 non-null     float64
 1   commission_pct  2 non-null      float64
dtypes: float64(2)
memory usage: 683.0+ bytes

    department_id      job_id        salary  commission_pct
0            10.0     AD_ASST   4400.000000             NaN
1            20.0      MK_MAN  13000.000000             NaN
2            20.0      MK_REP   6000.000000             NaN
3            30.0    PU_CLERK   2780.000000             NaN
4            30.0      PU_MAN  11000.000000             NaN
5            40.0      HR_REP   6500.000000             NaN
6            50.0    SH_CLERK   3215.000000             NaN
7            50.0    ST_CLERK   2785.000000             NaN
8            50.0      ST_MAN   7280.000000             NaN
9            60.0     IT_PROG   5760.000000             NaN
10           70.0      PR_REP  10000.000000             NaN
11           80.0      SA_MAN  12200.000000        0.300000
12           80.0      SA_REP   8396.551724        0.212069
13           90.0     AD_PRES  24000.000000             NaN
14           90.0       AD_VP  17000.000000             NaN
15          100.0  FI_ACCOUNT   7920.000000             NaN
16          100.0      FI_MGR  12000.000000             NaN
17          110.0  AC_ACCOUNT   8300.000000             NaN
18          110.0      AC_MGR  12000.000000             NaN

## 5) cut

In [6]:
# 读取员工数据
df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\employees.csv")

pd.cut(df.iloc[9:16]["salary"], 3)
pd.cut(df.iloc[9:16]["salary"], [0,10000,20000])
pd.cut(df.iloc[9:16]["salary"], 3, labels=["low", "medium", "high"])

9       high
10    medium
11    medium
12    medium
13    medium
14      high
15       low
Name: salary, dtype: category
Categories (3, str): ['low' < 'medium' < 'high']