# DataFrame的创建

In [51]:
import pandas as pd

# DataFrame可由多个Series组成
mango_series = pd.Series([4,5,6,3,1])
apple_series = pd.Series([5,4,3,0,2])
banana_series = pd.Series([2,3,5,2,7])
# 通过Series创建DataFrame 创建DataFrame对象
df = pd.DataFrame({'mango':mango_series, 'apple':apple_series, 'banana':banana_series})
# type(df)    pandas.DataFrame

# 通过字典创建DataFrame
df = pd.DataFrame({'id':[101,102,103],'name':['张三','李四',"王五"],'age':[20,30,40]})
df

# 通过字典创建DataFrame   在创建对象的同时  指定列的顺序(可以过滤)以及行标签
df = pd.DataFrame({'id':[101,102,103],'name':['张三','李四',"王五"],'age':[20,30,40]},columns=['name','age','id'],index=['aaa','bbb','ccc'])
df

    name  age   id
aaa   张三   20  101
bbb   李四   30  102
ccc   王五   40  103

# DataFrame的常用属性

In [52]:
df = pd.DataFrame(data={"id": [101, 102, 103], "name": ["张三", "李四", "王五"], "age": [20, 30, 40]},index=["aa", "bb", "cc"])
df
# index	DataFrame的行索引
df.index
# columns	DataFrame的列标签
df.columns
# values	DataFrame的值
df.values   # ndarray类型
# ndim	DataFrame的维度
df.ndim
# shape	DataFrame的形状
df.shape
# size	DataFrame的元素个数
df.size
# dtypes	DataFrame的元素类型
df.dtypes

# T	行列转置
df.T


# 通过中括号 获取列的数据 如果是多列,多列列名需要放到列表中
df[['id','name']]
# loc[]	显式索引，按行列标签索引或切片
# 取出aa和cc数据
df.loc[['aa','cc']]
df.loc[['aa','cc'],['name','age']]
# 取出aa到cc数据
df.loc['aa':'cc','id':'age']

# iloc[]	隐式索引，按行列位置索引或切片
df.iloc[:2,:2]
# at[]	使用行列标签访问单个元素
df.at['bb','name']
# iat[]	使用行列位置访问单个元素
df.iat[1,1]

'李四'

# DataFrame的常用方法

In [60]:
df = pd.DataFrame(data={"id": [101, 102, 103,104,105,106,101], "name": ["张三", "李四", "王五","赵六","冯七","周八","张三"], "age": [10, 20, 30, 40, None, 60,10]},index=["aa", "bb", "cc", "dd", "ee", "ff","aa"])
df
# head()	查看前n行数据，默认5行
df.head(3)
# tail()	查看后n行数据，默认5行
df.tail(3)
# isin()	元素是否包含在参数集合中
df.isin([103,'赵六',40])
# isna()	元素是否为缺失值
df.isna()
# sum()	求和
# mean()	平均值
# min()	最小值
# max()	最大值
# var()	方差
# std()	标准差
# median()	中位数
# mode()	众数
# quantile()	指定位置的分位数，如quantile(0.5)
# describe()	常见统计信息
# info()	基本信息
# value_counts()	每个元素的个数
# count()	非空元素的个数
# drop_duplicates()	去重
# sample()	随机采样
# replace()	用指定值代替原有值
# equals()	判断两个DataFrame是否相同
# cummax()	累计最大值
# cummin()	累计最小值
# cumsum()	累计和
# cumprod()	累计积
# diff()	一阶差分，对序列中的元素进行差分运算，也就是用当前元素减去前一个元素得到差值，默认情况下，它会计算一阶差分，即相邻元素之间的差值。参数：
# periods：整数，默认为 1。表示要向前或向后移动的周期数，用于计算差值。正数表示向前移动，负数表示向后移动。
# axis：指定计算的轴方向。0 或 'index' 表示按列计算，1 或 'columns' 表示按行计算，默认值为 0。
# sort_index()	按行索引排序
# sort_values()	按某列的值排序，可传入列表来按多列排序，并通过ascending参数设置升序或降序
# nlargest()	返回某列最大的n条数据
# nsmallest()	返回某列最小的n条数据

       id   name    age
aa  False  False  False
bb  False  False  False
cc  False  False  False
dd  False  False  False
ee  False  False   True
ff  False  False  False
aa  False  False  False