# Agg统计多个值

In [9]:
import pandas as pd

# 读取员工数据
df = pd.read_csv(r"D:\AAAjobbing\actfirst\Numpy&Pandas\data\employees.csv")

# 一次计算多个统计值
# 按department_id分组, 计算salary的最小值,中位数,最大值
df.groupby('department_id')['salary'].agg(['min','median','max'])

                   min   median      max
department_id
10.0            4400.0   4400.0   4400.0
20.0            6000.0   9500.0  13000.0
30.0            2500.0   2850.0  11000.0
40.0            6500.0   6500.0   6500.0
50.0            2100.0   3100.0   8200.0
60.0            4200.0   4800.0   9000.0
70.0           10000.0  10000.0  10000.0
80.0            6100.0   8900.0  14000.0
90.0           17000.0  17000.0  24000.0
100.0           6900.0   8000.0  12000.0
110.0           8300.0  10150.0  12000.0

In [12]:
# 针对不同的聚合字段进行不同的聚合操作
# 按department_id分组，统计job_id的种类数，commission_pct的平均值
df.groupby('department_id').agg({'job_id':'nunique','commission_pct':'mean'})

               job_id  commission_pct
department_id
10.0                1             NaN
20.0                2             NaN
30.0                2             NaN
40.0                1             NaN
50.0                3             NaN
60.0                1             NaN
70.0                1             NaN
80.0                2           0.225
90.0                2             NaN
100.0               2             NaN
110.0               2             NaN